services:
  francauto:
    build: .
    container_name: francauto-app
    command: python -m backend.app   # ðŸ‘ˆ ADD THIS LINE
    ports:
      - "5000:5000"  # Flask backend
    volumes:
      - ./backend:/app/backend
      - ./backend/instance:/app/backend/instance
    environment:
      FLASK_APP: backend.app
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      VITE_API_URL: "http://localhost:5000"
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
